---
- name: Fail if Operating System is not Supported
  fail:
    msg: "Minimum Operating System Version Ubuntu 14.04"
  when:
    - ansible_distribution != 'Ubuntu'
    - ansible_distribution_major_version | int >= 14

- name: Get Service Init Status
  stat:
    path: /sbin/init
  register: service_init_status

- name: Get ZFS Block Device Status
  stat:
    path: "/dev/{{ zfs_block_device }}"
  register: zfs_block_status
  when:
    - zfs_block_device is defined

- name: Get ZFS Block Device Info
  parted:
    device: "/dev/{{ zfs_block_device }}"
    unit: MiB
  register: zfs_block_info
  when:
    - zfs_block_device is defined
    - zfs_block_status.stat.exists

- name: Set Host Facts
  set_fact:
    full_uninstall: "{{ full_uninstall | default(default_value, true) }}"
    galera_distribution: "{{ galera_distribution | default(default_value, true) }}"
    galera_version_major: "{{ galera_version_major | default(default_value, true) }}"
    galera_version_minor: "{{ galera_version_minor | default(default_value, true) }}"
    zfs_backend: "{{ zfs_backend if zfs_block_device is defined else 'false' | default(default_value, true) }}"
    zfs_block_wipe: "{{ zfs_block_wipe if zfs_block_device is defined else 'false' | default(default_value, true) }}"
    zfs_pool_name: "{{ zfs_pool_name | default(default_value, true) }}"
    zfs_pool_wipe: "{{ zfs_pool_wipe | default(default_value, true) }}"
    zfs_dataset_wipe: "{{ zfs_dataset_wipe | default(default_value, true) }}"

- name: Make Sure ZFS Backend not Enabled if ZFS Block Device not Exist
  set_fact:
    zfs_backend: 'false'
  when:
    - zfs_backend
    - not zfs_block_status.stat.exists

- name: Make Sure ZFS Backend not Enabled if Node is a Load Balancer Node
  set_fact:
    zfs_backend: 'false'
  when:
    - zfs_backend
    - inventory_hostname in groups['galera_lb']
