---
- include: facts.yml

- include: haproxy_services.yml
  when:
    - inventory_hostname in groups['galera_lb']

- include: haproxy_cleanups.yml
  when:
    - inventory_hostname in groups['galera_lb']

- include: haproxy_packages.yml
  when:
    - full_uninstall
    - inventory_hostname in groups['galera_lb']

- include: galera_services.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_cleanups.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: zfs_mounts.yml
  when:
    - full_uninstall
    - zfs_backend
    - inventory_hostname in groups['galera_node']

- include: galera_directories.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_packages.yml
  when:
    - full_uninstall
    - inventory_hostname in groups['galera_node']

- include: galera_users.yml
  when:
    - full_uninstall
    - inventory_hostname in groups['galera_node']

- include: zfs_blocks.yml
  when:
    - full_uninstall
    - zfs_backend
    - inventory_hostname in groups['galera_node']
