---
# Default Value for Full Uninstall
full_uninstall: 'false'

# Default Value for Galera Distribution
galera_distribution: 'percona'

# Default Value for MariaDB Galera Major Version
galera_version_major: '5'

# Default Value for MariaDB Galera Minor Version
galera_version_minor: '7'

# Default Value MariaDB Galera Cluster Name
galera_cluster_name: 'galera'

# Default Value for ZFS Backend Storage
zfs_backend: 'false'

# Default Value for ZFS Block Wipe
zfs_block_wipe: 'false'

# Default Value for ZFS Pool Name
zfs_pool_name: 'data'

# Default Value for ZFS Pool Wipe
zfs_pool_wipe: 'false'

# Default Value for ZFS Dataset Wipe
zfs_dataset_wipe: 'false'
