---
- name: Create Galera Databases Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: true
  with_items:
    - /var/lib/mysql

- name: Create Galera Configurations Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    recurse: true
  with_items:
    - /etc/mysql

- name: Create Galera Run Directory
  file:
    path: "{{ item }}"
    state: directory
    owner: mysql
    group: mysql
    recurse: true
  with_items:
    - /var/run/mysqld

- name: Create Galera Logs File
  file:
    path: "{{ item }}"
    state: touch
    owner: mysql
    group: mysql
  with_items:
    - /var/log/mysqld.log
