---
- name: Remove AppArmor Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    autoremove: yes
    autoclean: yes
    state: absent
  with_items:
    - apparmor
  when:
    - galera_distribution == 'percona'

- name: Download Galera Repository Package
  shell: wget -O /tmp/percona-release_0.1-6.$(lsb_release -sc)_all.deb https://repo.percona.com/apt/percona-release_0.1-6.$(lsb_release -sc)_all.deb
  args:
    warn: false
  when:
    - galera_distribution == 'percona'

- name: Install Galera Repository
  shell: dpkg --install /tmp/percona-release_0.1-6.$(lsb_release -sc)_all.deb
  args:
    warn: false
  when:
    - galera_distribution == 'percona'

- name: Remove Downloaded Galera Repository Package
  shell: rm -f /tmp/percona-release_0.1-6.$(lsb_release -sc)_all.deb || true
  args:
    warn: false
  when:
    - galera_distribution == 'percona'

- name: Install Galera Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - percona-xtradb-cluster-garbd-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-common-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-server-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-client-{{ galera_version_major }}.{{ galera_version_minor }}
    - percona-xtradb-cluster-galera-3.x
    - percona-xtrabackup-24
  when:
    - galera_distribution == 'percona'

- name: Install Galera Cluster Check Packages
  apt:
    name: "{{ item }}"
    force_apt_get: yes
    update_cache: yes
    autoremove: yes
    autoclean: yes
    state: present
  with_items:
    - xinetd

- name: Enable Galera Cluster Check as Know Services
  lineinfile:
    path: /etc/services
    insertafter: '^# Local services'
    line: 'mysqlchk    9200/tcp      # MySQL Check'
    create: yes
    state: present
