---
- include: facts.yml

- include: os_packages.yml

- include: python_packages.yml

- include: zfs_packages.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['galera_node']

- include: zfs_blocks.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['galera_node']

- include: galera_users.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_packages.yml
  when:
    - inventory_hostname in groups['galera_node']
    
- include: galera_services.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_cleanups.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: zfs_mounts.yml
  when:
    - zfs_backend
    - inventory_hostname in groups['galera_node']

- include: galera_directories.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: galera_init_root.yml
  when:
    - inventory_hostname in groups['galera_node']

- include: haproxy_packages.yml
  when:
    - inventory_hostname in groups['galera_lb']

- include: haproxy_services.yml
  when:
    - inventory_hostname in groups['galera_lb']

- include: haproxy_cleanups.yml
  when:
    - inventory_hostname in groups['galera_lb']
